import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
//import styles from '@/styles/Home.module.css'
import { Container,Box,Typography,Card,CssBaseline } from '@mui/material'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <CssBaseline />
      <Container style={{marginTop: "5rem",textAlign: "left"}}>
      <Typography variant='h2'sx={{textAlign: "left",fontWeight: "900"}}>
        Welcome to 
        <br /> StudySync
      </Typography>
      <Typography variant='h5'sx={{fontWeight: "300",mt: "1rem"}}>
        The lectures app
      </Typography>
      <img src='bg-image.svg' style={{float: "right"}} />
      </Container>
    </main>

    </>
  )
}
